wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    is_jupyter_run: true
    is_kaggle_kernel: true
    python_version: 3.10.6
    start_time: 1669917004.72788
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 23
      4: 3.10.6
      5: 0.13.5
      8:
      - 1
      - 2
      - 5
